name: Build Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from Dockerfile
      shell: bash
      run: echo "VERSION=$(grep -oP '(?<=ARG QBITTORRENT_VERSION=)[^ ]+' Dockerfile)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      id: build-and-push
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        platforms: linux/amd64
        file: Dockerfile
        context: .

    - name: Attest
      uses: actions/attest-build-provenance@v2
      id: attest
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build-and-push.outputs.digest }}
        push-to-registry: true

    - name: Sign the image
      run: |
        cosign sign --yes \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
      env:
        COSIGN_EXPERIMENTAL: 1

    - name: Verify the pushed tags
      run: |
        cosign verify --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          --certificate-identity-regex "https://github.com/d4rkfella/*" \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
      env:
        COSIGN_EXPERIMENTAL: 1
