name: Build Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      IMAGE_NAME: qbittorrent-distroless
      FULCIO_URL: "https://fulcio.sigstore.dev"
      REKOR_URL: "https://rekor.sigstore.dev"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Set up Cosign
      uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

    - name: Construct version tags
      shell: bash
      run: |
        VERSION=$(grep -oP '(?<=ARG VERSION=)[^ ]+' Dockerfile)
        echo "VERSION_STRIPPED=$(echo "$VERSION" | sed 's/^release-//; s/_v[0-9.]*$//')" >> $GITHUB_ENV
        echo "MAJOR_VERSION=$(echo "${{ env.VERSION_STRIPPED }}" | cut -d'.' -f1)" >> $GITHUB_ENV
        echo "MAJOR_MINOR_VERSION=$(echo "${{ env.VERSION_STRIPPED }}" | cut -d'.' -f1,2)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
      id: build-and-push
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_STRIPPED }}
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_MINOR_VERSION }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}
          org.opencontainers.image.url=https://ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.vendor=${{ github.repository_owner }}
        platforms: linux/amd64
        file: Dockerfile
        context: .

    - name: Sign the image
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign --yes ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }} \
            --fulcio-url ${{ env.FULCIO_URL }}  --rekor-url ${{ env.REKOR_URL }} \
            -a sha=${{ github.sha }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }}

    - name: Verify the pushed tags
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign verify --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          --certificate-identity-regexp "https://github.com/d4rkfella/*" \
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
